export const FETCH_PRODUCTS_DATA = "FETCH_PRODUCTS_DATA";
export const FETCH_SUCCESS_DATA = "FETCH_SUCCESS_DATA";
export const FETCH_FAILER_DATA = "FETCH_FAILER_DATA";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const SEARCH_RESULT = "SEARCH_RESULT";
